const ActionTypes = {
    CURRENTUSER: 'CURRENTUSER',
    CURRENTUSERUID: 'CURRENTUSERUID',
    ALLUSERS: 'ALLUSERS',
    USERDATAARRAY: 'USERDATAARRAY',
    UNLIKEARRAY: 'UNLIKEARRAY',
    MEETINGSARRAY: 'MEETINGSARRAY',
    REQUESTSARRAY: 'REQUESTSARRAY',
    CHANGES: "CHANGES"
}

export default ActionTypes;
